import { Schema, model } from 'mongoose';

/**
 * KnowledgeTopic — a product-wide, tree-structured markdown document per
 * subject (İletişim, Hakkımızda, Fiyatlandırma, ...), assembled by
 * `packages/ai/src/site-topics.js`'s map-reduce pass over a URL/API crawl's
 * pages (`apps/worker-ingestion/src/handlers/ingest-source.js`).
 *
 * Distinct from `KnowledgeSource`/`KnowledgeChunk`: a source is one crawl
 * input (one URL root), a topic is a cross-source, cross-page *subject* —
 * the same "İletişim" topic can be composed from a footer snippet on one
 * page and a dedicated /contact page on another. `sourcePages` is the only
 * link back to where the content actually came from.
 *
 * `body` is also chunked/embedded into `KnowledgeChunk` (via the same
 * `ingestSource()` pipeline every other segment goes through — see
 * ingest-source.js) so `search_knowledge` retrieval benefits from it
 * directly; those chunks carry `metadata.topicId` and `KnowledgeChunk.topicId`
 * instead of `sourceId` (see KnowledgeChunk.js).
 */
const KnowledgeTopicSchema = new Schema(
    {
        productId: { type: Schema.Types.ObjectId, ref: 'Product', required: true, index: true },
        // Stable, URL/lookup-safe identifier — e.g. 'iletisim', or a
        // dedup'd slug for a site-specific topic (see dedupeProposedTopics()).
        slug: { type: String, required: true },
        title: { type: String, required: true },
        parentTopicId: { type: Schema.Types.ObjectId, ref: 'KnowledgeTopic', default: null, index: true },
        body: { type: String, default: '' },
        // false for the fixed starter taxonomy (seeded empty at first crawl),
        // true for a topic the map phase proposed and dedupeProposedTopics()
        // created — surfaced in the Console so a customer knows to review it.
        autoGenerated: { type: Boolean, default: false },
        status: { type: String, enum: ['pending', 'processing', 'ready', 'failed'], default: 'pending' },
        error: { type: String },
        sourcePages: {
            type: [
                {
                    sourceId: { type: Schema.Types.ObjectId, ref: 'KnowledgeSource', required: true },
                    pageUrl: { type: String, required: true }
                }
            ],
            default: []
        },
        // The exact set of pageUrls that fed the current `body` — compared
        // against each re-ingest's contributing-page set so an unchanged
        // topic's (expensive) reduce pass can be skipped. Not the same as
        // sourcePages' shape (no sourceId needed for the diff) to keep the
        // comparison a plain string-array equality check.
        lastContributingPages: { type: [String], default: [] }
    },
    { timestamps: true }
);

KnowledgeTopicSchema.index({ productId: 1, slug: 1 }, { unique: true });

export const KnowledgeTopic = model('KnowledgeTopic', KnowledgeTopicSchema);
